# Generated by Django 6.0.5 on 2026-05-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('junior', 'Junior'), ('adult', 'Adult'), ('vip', 'VIP')], default='adult', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
